# Generated by Django 5.2.6 on 2025-10-01 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Customer/Client name', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('company', models.CharField(blank=True, help_text='Company/Organization', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Can access APIs')),
                ('access_token_lifetime_hours', models.IntegerField(default=24, help_text='Access token lifetime in hours')),
                ('refresh_token_lifetime_days', models.IntegerField(default=30, help_text='Refresh token lifetime in days')),
                ('last_access', models.DateTimeField(blank=True, help_text='Last API access', null=True)),
                ('total_requests', models.PositiveIntegerField(default=0, help_text='Total API requests made')),
                ('created_by', models.CharField(help_text='Admin who created this token user', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token User',
                'verbose_name_plural': 'Token Users',
                'db_table': 'token_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], max_length=10)),
                ('token', models.CharField(help_text='The actual token string', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Token description', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='How many times this token was used')),
                ('last_ip', models.GenericIPAddressField(blank=True, help_text='Last IP address used', null=True)),
                ('last_user_agent', models.TextField(blank=True, help_text='Last user agent')),
                ('token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='authentication.tokenuser')),
            ],
            options={
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='api_tokens_token_8d7e16_idx'), models.Index(fields=['token_user', 'token_type', 'is_active'], name='api_tokens_token_u_1ceb9a_idx'), models.Index(fields=['expires_at', 'is_active'], name='api_tokens_expires_2f81fc_idx')],
            },
        ),
    ]
