# Generated by Django 5.2.6 on 2025-10-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Noor API')", max_length=100, unique=True)),
                ('url_pattern', models.CharField(help_text="URL pattern (e.g., 'api/v1/noor/')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this endpoint does')),
                ('category', models.CharField(choices=[('student_services', 'Student Services'), ('verification', 'Verification Services'), ('erp', 'ERP Integration'), ('banner', 'Banner Database'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this endpoint available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'db_table': 'api_endpoints',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['url_pattern'], name='api_endpoin_url_pat_bd77a5_idx'), models.Index(fields=['is_active'], name='api_endpoin_is_acti_b59fc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When permission was granted')),
                ('granted_by', models.CharField(blank=True, help_text='Admin who granted this permission', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Why this permission was granted')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='authentication.apiendpoint')),
                ('token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_permissions', to='authentication.tokenuser')),
            ],
            options={
                'verbose_name': 'Token Permission',
                'verbose_name_plural': 'Token Permissions',
                'db_table': 'token_permissions',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddField(
            model_name='tokenuser',
            name='allowed_endpoints',
            field=models.ManyToManyField(blank=True, help_text='Endpoints this token user can access', related_name='token_users', through='authentication.TokenPermission', to='authentication.apiendpoint'),
        ),
        migrations.AddIndex(
            model_name='tokenpermission',
            index=models.Index(fields=['token_user', 'endpoint'], name='token_permi_token_u_41a5fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenpermission',
            unique_together={('token_user', 'endpoint')},
        ),
    ]
